using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._SilkNebula.Cyberpunk.Surgery;

[GenerateTypedNameReferences]
public sealed partial class CyberSurgeryGui : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action<EntityUid>? OnSurgeryButtonPressed;
    public event Action<EntityUid>? OnCyberneticsSlotPressed;
    public event Action<string>? OnBodyPartSelected;

    private EntityUid _targetEntity;
    private bool _isSurgeryMode = true;

    public AdwancedSurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetupEventHandlers();
        SwitchToSurgeryMode();
    }

    private void SetupEventHandlers()
    {
        // Обработка вкладок
        SurgeryTab.OnPressed += _ => SwitchToSurgeryMode();
        CyberneticsTab.OnPressed += _ => SwitchToCyberneticsMode();

        // Обработка кнопок
        HeadButton.OnPressed += _ => OnBodyPartSelected?.Invoke("Head");
        TorsoButton.OnPressed += _ => OnBodyPartSelected?.Invoke("Torso");
        LeftArmButton.OnPressed += _ => OnBodyPartSelected?.Invoke("LeftArm");
        RightArmButton.OnPressed += _ => OnBodyPartSelected?.Invoke("RightArm");
        LeftLegButton.OnPressed += _ => OnBodyPartSelected?.Invoke("LeftLeg");
        RightLegButton.OnPressed += _ => OnBodyPartSelected?.Invoke("RightLeg");

        // Обработка слотов кибернетики
        HeadSlotButton.OnPressed += _ => OnCyberneticsSlotPressed?.Invoke(_targetEntity);
        TorsoSlotButton.OnPressed += _ => OnCyberneticsSlotPressed?.Invoke(_targetEntity);
        LeftArmSlotButton.OnPressed += _ => OnCyberneticsSlotPressed?.Invoke(_targetEntity);
        RightArmSlotButton.OnPressed += _ => OnCyberneticsSlotPressed?.Invoke(_targetEntity);
        LeftLegSlotButton.OnPressed += _ => OnCyberneticsSlotPressed?.Invoke(_targetEntity);
        RightLegSlotButton.OnPressed += _ => OnCyberneticsSlotPressed?.Invoke(_targetEntity);
    }

    private void SwitchToSurgeryMode()
    {
        _isSurgeryMode = true;
        SurgeryTab.Pressed = true;
        CyderneticsTab.Pressed = false;

        SurgeryDoll.Visible = true;
        CyberneticsDoll.Visible = false;

        UpdateWindowTitle("Режим операции")
    }

    private void SwitchToCyberneticsMode()
    {
        _isSurgeryMode = true;
        SurgeryTab.Pressed = false;
        CyderneticsTab.Pressed = true;

        SurgeryDoll.Visible = false;
        CyberneticsDoll.Visible = true;

        UpdateWindowTitle("Режим кибернетики");
    }

    public void SetTargetEntity(EntityUid entity)
    {
        _targetEntity = entity;
        UpdateTargetInfo();
    }

    private void UpdateTargetInfo()
    {
        if (!_entityManager.TryGetComponent(_targetEntity, out MetaDataComponent? metaData))
            return;

        TargetName.Text = metaData.EntityName;
    }
}
